apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkousers.kafka.appfarm.rs
spec:
  group: kafka.appfarm.rs
  names:
    plural: kafkousers
    singular: kafkouser
    kind: KafkaUser
    shortNames:
      - kuser
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                topic:
                  type: string
                  description: Topic to grant access
                permissions:
                  type: string
                  enum: ["read", "write", "admin"]
                  description: Permissions for the user
              required:
                - topic
                - permissions
            status:
              type: object
              properties:
                conditions:
                  type: array
                  description: "List of observed states of the resource"
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: "Type of condition"
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                        description: "Status of condition"
                      lastTransitionTime:
                        type: string
                        format: date-time
                        description: "Last time the condition transitioned from one status to another"
                      reason:
                        type: string
                        description: "Reason for the condition's last transition"
                      message:
                        type: string
                        description: "Human-readable message indicating details about the transition"
                    required:
                      - type
                      - status
                      - lastTransitionTime
      additionalPrinterColumns:
        - name: Topic
          type: string
          jsonPath: .spec.topic
        - name: Permissions
          type: string
          jsonPath: .spec.permissions
        - name: Status
          type: string
          jsonPath: .status.conditions[?(@.type=='Created')].status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  conversion:
    strategy: None